#!/usr/bin/env python3
# Generated by: Cerebras (llm_router)
# Refined by: Claude Code (argument passing fixes)
"""
Kart CLI Wrapper - Simple frontend for backend task execution

Usage:
    python kart.py "task description"
    python kart.py --status
    python kart.py --tasks
    python kart.py --resume artifacts/kart/sessions/7KE2N.json
    python kart.py --tools
"""

import os
import subprocess
import sys
from pathlib import Path

def main():
    # Get Willow root (where this script lives)
    willow_root = Path(__file__).parent.absolute()

    # Path to actual kart CLI
    kart_cli = willow_root / "cli" / "kart_cli.py"

    if not kart_cli.exists():
        print(f"Error: kart_cli.py not found at {kart_cli}")
        return 1

    # Change to Willow root for execution
    os.chdir(willow_root)

    # Build subprocess args
    cmd = [sys.executable, str(kart_cli)] + sys.argv[1:]

    # Execute kart_cli.py with all arguments passed through
    try:
        exit_code = subprocess.call(cmd)
        return exit_code
    except KeyboardInterrupt:
        print("\n\nInterrupted by user")
        return 130
    except Exception as e:
        print(f"Error: {e}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
